name: CI Pipeline

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Utiliser Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Installer les dépendances
      run: npm ci
    
    - name: Exécuter les tests
      run: npm test
      env:
        CI: true
    
    - name: Build l'application
      run: npm run build || echo "No build script"
    
    - name: Upload l'artefact de build
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          src/
          package.json
          package-lock.json